name: Build Electron App

on:
  push:
    tags:
    - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: build and release electron app

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2019, macos-13 ]
        node: [ '22.2.0' ]
        python: [ '3.9' ]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          cd electron && npm install

      - name: Build assets
        run: npm run build-electron

      - name: Build mac dmg
        if: matrix.os == 'macos-13'
        run: |
          cd electron
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build windows exe
        if: matrix.os == 'windows-2019'
        run: |
          cd electron
          npm run build-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'macos-13'
        with:
          name: mac-artifacts
          path: |
            electron/dist/app/FreeTexturePacker-*.dmg
            electron/dist/app/FreeTexturePacker-*.dmg.blockmap
            electron/dist/app/latest-mac.yml

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-2019'
        with:
          name: windows-artifacts
          path: |
            electron/dist/app/FreeTexturePacker-*.exe
            electron/dist/app/FreeTexturePacker-*.exe.blockmap
            electron/dist/app/latest.yml
